main: main.java.io.github.bytelab.wormholes.main
version: 1.0
name: Wormholes
description: >
             Plugin for a fancier form of teleportation!
commands:
  wh:
    description: Base command for Wormholes
  wormhole:
    description: Base command for Wormholes